services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    env_file:
      - ./env/.env.dev
    build:
      context: .
      dockerfile: Dockerfile.db

  lotus:
    container_name: lotus_django
    env_file:
      - ./env/.env.dev
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./lotus:/lotus
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py initadmin &&
             python3 manage.py setup_tasks &&
             python3 manage.py runserver 0.0.0.0:8000
             "
    depends_on:
      - db

  frontend:
    restart: always
    command: yarn dev
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - lotus

  redis:
    image: redis:7-alpine
    command: redis-server
    env_file:
      - ./env/.env.dev

  celery:
    env_file:
      - ./env/.env.dev
    build:
      context: .
    command: celery -A lotus worker -l info
    volumes:
      - ./lotus:/lotus
    depends_on:
      - db
      - redis
      - lotus
  celery-beat:
    env_file:
      - ./env/.env.dev
    restart: on-failure
    build:
      context: .
    command: celery -A lotus beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./lotus:/lotus
    depends_on:
      - celery
      - redis
      - lotus
      - db
volumes:
  pgdata:
